name: Release

on:
  workflow_dispatch:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        if: github.ref != 'refs/heads/master'
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          skipIfReleaseExists: true

  build:
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ {platform: 'linux/amd64', name: 'x86_64'}, {platform: 'linux/arm64', name: 'aarch64'}]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build ${{ matrix.arch.platform }}
      run: make PLATFORM=${{ matrix.arch.platform }} one

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./out/zerotier-one-${{ matrix.arch.name }}.tar.gz



